set expandtab
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4

syntax on

set nu

set showmode
set showcmd
set wildmenu

set noswapfile

set t_Co=256
let g:gruvbox_italic=1
colorscheme gruvbox

set noerrorbells
set novisualbell

set encoding=utf8

set mouse=a

set hlsearch
set scroll=1

"" Ariline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = '    '
let g:airline#extensions#tabline#left_alt_sep = '||'
let g:airline#extensions#tabline#formatter = 'default'
let g:airline_theme='supernova'

" Emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_leader_key='<C-Z>'

call plug#begin()

Plug 'mattn/emmet-vim'

call plug#end()

""----------------------------------------------
" folding
"-----------------------------------------------
" set foldenable
" set foldmethod=indent
" set foldminlines=4
" set foldnestmax=4

" let g:markdown_folding=1
